trigger:
  - master

pr: none

steps:

- script: |
    sudo npm install -g serverless
    npm install
  displayName: 'Install dependencies'

- script: |
    sls deploy
  displayName: 'Deploy with Serverless'


