trigger:
  - master

pr: none

steps:

- script: |
    npm install serverless -g && npm install
  displayName: 'Install dependencies'

- script: |
    sls deploy
  displayName: 'Deploy with Serverless'


